---

gce_credentials_file: 'secrets/service-credentials.json'

gce_service_account_email: "{{ lookup('file', gce_credentials_file) | from_json | json_query('client_email') }}"
gce_project_id: "{{ lookup('file', gce_credentials_file) | from_json | json_query('project_id') }}"

gce_region: europe-west3
gce_zone: europe-west3-a

gce_network_name: kubernetes-the-hard-way
gce_subnet_name: kubernetes

kubernetes_controller_count: 3
kubernetes_worker_count: 3

kubernetes_local_certs_dir: '{{ playbook_dir }}/certs/'

cfssl_ca_dir: '/opt/ca'
cfssl_ca_certs_dir: '{{ cfssl_ca_dir }}/certs'
cfssl_ca_conf_dir: '{{ cfssl_ca_dir }}/conf'
cfssl_ca_request_dir: '{{ cfssl_ca_dir }}/requests'

cfssl_ca_user: vagrant
cfssl_ca_group: vagrant
