---

- name: Master component configuration
  import_role:
    name: 'kube-master-component'
  vars: 
    kube_master_component_name: kube-proxy
    kube_master_component_server_ip: '{{ kubernetes_api_static_ip_address }}'
    kube_master_component_data_dir: '{{ kube_proxy_data_dir }}'
    kube_master_component_bin_dir: '{{ kube_proxy_bin_dir }}'

    
# TODO service handling