---

- hosts: all
  tags: always 
  tasks:
    - name: Get public API ip address 
      local_action: >
        command gcloud compute addresses describe {{ kubernetes_api_static_ip_address_name }} 
        --region {{ gce_region }}
        --format 'value(address)'
      changed_when: false
      register: kubernetes_api_static_ip_address_result
      run_once: true

    - name: Set public API ip address to fact
      set_fact: 
        kubernetes_api_static_ip_address: '{{ kubernetes_api_static_ip_address_result.stdout }}'

- hosts: certificate-authorities
  roles: 
    - cfssl-ca
  tags: ca

- hosts: localhost
  roles:
    - kube-common

- hosts: kubernetes-clients
  roles: 
    - kubernetes-client
  tags: clients

- hosts: tag_controller
  roles: 
    - etcd
    - kube-apiserver
    - kube-proxy
    - kube-scheduler
    - kube-controller-manager
  tags: controllers

- hosts: tag_worker
  roles: 
    - kubernetes-worker
    - kube-proxy
  tags: workers