---

- hosts: certificate-authorities
  roles: 
    - cfssl-ca
  tags: ca

- hosts: kubernetes-clients
  roles: 
    - kubernetes-client
  tags: clients

- hosts: tag_controller
  roles: 
    - kubernetes-controller
  tags: controllers

- hosts: tag_worker
  roles: 
    - kubernetes-worker
    - kube-proxy
  tags: workers