--- 

- hosts: localhost
  gather_facts: false
  tasks: 
  - name: Create network
    local_action:
      module: gce_net
      name: '{{ gce_network_name }}'
      mode: custom
      subnet_name: kubernetes
      subnet_region: '{{ gce_region }}'
      ipv4_range: '10.240.0.0/24'
      state: present
      credentials_file: '{{ gce_credentials_file }}'
      service_account_email: '{{ gce_service_account_email }}'
      project_id: '{{ gce_project_id }}'

  - name: Firewall rules to allow vm's to access each other
    local_action:
      module: gce_net
      name: '{{ gce_network_name }}'
      fwname: 'kubernetes-the-hard-way-allow-internal'
      allowed: '{{ item[0] }}'
      state: 'present'
      src_range: '{{ item[1] }}'
      credentials_file: '{{ gce_credentials_file }}'
      service_account_email: '{{ gce_service_account_email }}'
      project_id: '{{ gce_project_id }}'
    with_nested: 
      - [tcp, udp, icmp]
      - ['10.200.0.0/16', '10.240.0.0/24']

  - name: Firewall rules to allow public access
    local_action:
      module: gce_net
      name: '{{ gce_network_name }}'
      fwname: 'kubernetes-the-hard-way-allow-external'
      allowed: '{{ item[0] }}'
      state: 'present'
      src_range: '{{ item[1] }}'
      credentials_file: '{{ gce_credentials_file }}'
      service_account_email: '{{ gce_service_account_email }}'
      project_id: '{{ gce_project_id }}'
    with_nested: 
      - ['tcp:22', 'tcp:6443', icmp]
      - ['0.0.0.0/0']