---

kube_apiserver_data_dir: /var/lib/kubernetes
kube_apiserver_bin_dir: /usr/local/bin

kubernetes_etcd_client_port: 2379

kube_apiserver_encryption_config_local: '{{ kubernetes_local_configs_dir }}/encryption_config.yml'
